targets:
    distcheck:
        task_args:
            - ./pkg/...
    dist-linux-amd64:
        task_args:
            - -ldflags
            - "-X github.com/rafaelmartins/simplevirt.Version={{.Version}}"
