targets:
    distcheck:
        task_args:
            - ./internal/...
    dist-linux-amd64:
        task_args:
            - -ldflags
            - "-X github.com/rafaelmartins/simplevirt/internal/version.Version={{.Version}}"
